### ISSUE TITLE
Add basic package CVE search

### ISSUE THREAD

**Issue by mdingwall** [integratedcomputersolutions/icsbom#11]
There is a need to be able to search the NVD cache for a specific package/vendor combination.  This needs to probably have the ability to add this additional argument:

`-l '[package_description]'`
`--lookup '[package_description]'`

where `'[package_description]'` can look like this:
  - `'product=git'`
  - `'vendor=git;product=git;version=2.*'`
  - `'product=git;version=2.*'`

The package must have a product in the description to make it valid.  The `'*'` glob should be allowed in the tags to help find variations of the product.

# Tasks
- [x] Add the `-l`|`--lookup` argument.
- [x] Create a processing method to parse the list of packages found in the argument list.
- [x] Rework how the main function sends this data to the CveMatcher class from [ics-sbom-libs](https://github.com/integratedcomputersolutions/ics-sbom-libs)
- [ ] Look into version globing *(this may not be necessary)* 

**THIS IS DEPENDENT ON:** integratedcomputersolutions/ics-sbom-libs#18
